server:
  port: 8084
spring:
  application:
    name: hn-order-service
  datasource:
    url: jdbc:postgresql://localhost:5434/hn_order_service
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        order_by:
          default_null_ordering: last
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

jwt:
  signer-key: ${SECRET_KEY}
  issuer: hn-ecommerce

services:
  product-url: http://localhost:8080/api/v1/product
  inventory-url: http://localhost:8080/api/v1/inventory
